---
- name: Add non-root user to the lxd group
  user:
    name: "{{ local_non_root_user }}"
    groups: lxd
    append: yes
    state: present


- name: Copy LXD preseed file from template
  template:
    mode: 0640
    owner: "{{ local_non_root_user }}"
    group: "{{ local_non_root_user }}"
    dest: /home/{{ local_non_root_user }}/preseed.yml
    src: preseed.yml.j2
    force: yes
    backup: yes
  register: lxd_preseed_changes_made


- name: Initialise LXD with preseed file
  shell:
    cmd: lxd init --preseed < /home/{{ local_non_root_user }}/preseed.yml
  when:
    - lxd_preseed_changes_made is changed


    - name: Add ubuntu-minimal LXD remote
  shell:
    cmd: 'lxc remote add --protocol="simplestreams" ubuntu-minimal https://cloud-images.ubuntu.com/minimal/releases/'
  become: yes
  become_user: "{{ local_non_root_user }}"
