---

# Copy iptables rules script (making executable)
#
- name: Copy firewall rules script
  template:
    mode: 0770
    owner: root
    group: root
    dest: /usr/local/bin/iptables-rules.sh
    src: iptables-rules.sh.j2
    force: yes


# Copy firewall service definition
#
- name: Copy firewall service definition
  copy:
    mode: 0644
    owner: root
    group: root
    dest: /lib/systemd/system/iptables-rules.service
    src: iptables-rules.service
    force: yes


# Enable iptables rules service
#
- name: Enable firewall service
  service:
    name: iptables-rules.service
    enabled: yes
    state: started


# Set up HAProxy certs directory
#
- name: Create the `/etc/haproxy/ssl` directory
  file:
    path: /etc/haproxy/ssl/
    state: directory
    mode: 0755


# Set up HAProxy configuration
#
- name: Push haproxy config file
  template:
    mode: 0644
    owner: root
    group: root
    dest: /etc/haproxy/haproxy.cfg
    src: haproxy.cfg.j2
    force: yes


# Add a cronjob to reload the HAProxy configuration every day
#
- name: Add haproxy reload cronjob
  cron:
    name: "haproxy reload"
    special_time: daily
    job: "systemctl reload haproxy"
    state: present


# Create webhook working directory
#
- name: Create webhook working directory
  file:
    path: /var/webhook
    state: directory
    mode: '0755'


# Copy webhook configuration
#
- name: Copy webhook configuration
  copy:
    mode: 0660
    owner: root
    group: root
    dest: /usr/local/bin/hooks.yaml
    src: hooks.yaml
    force: yes


# Copy haproxy reload script
#
- name: Copy haproxy reload script
  copy:
    mode: 0770
    owner: root
    group: root
    dest: /usr/local/bin/reload-haproxy.sh
    src: reload-haproxy.sh
    force: yes


# Copy webhook start script
#
- name: Copy webhook start script
  copy:
    mode: 0770
    owner: root
    group: root
    dest: /usr/local/bin/start-webhook.sh
    src: start-webhook.sh
    force: yes


# Copy webhook service definition
#
- name: Copy webhook service definition
  copy:
    mode: 0644
    owner: root
    group: root
    dest: /lib/systemd/system/webhook.service
    src: webhook.service
    force: yes


#Enable webhook service
#
- name: Enable webhook service
  service:
    name: webhook.service
    enabled: yes
    state: started
