---

# Copy iptables rules script (making executable)
#
- name: Copy firewall rules script
  copy:
    mode: 0770
    owner: root
    group: root
    dest: /usr/local/bin/iptables-rules.sh
    src: iptables-rules.sh
    force: yes


# Copy firewall service definition
#
- name: Copy firewall service definition
  copy:
    mode: 0644
    owner: root
    group: root
    dest: /lib/systemd/system/iptables-rules.service
    src: iptables-rules.service
    force: yes


# Enable iptables rules service
#
- name: Enable firewall service
  service:
    name: iptables-rules.service
    enabled: yes
    state: started


# Set up HAProxy certs directory
#
- name: Create the `/etc/haproxy/ssl` directory
  file:
    path: /etc/haproxy/ssl/
    state: directory
    mode: 0755


# Set up HAProxy configuration
#
- name: Push haproxy config file
  template:
    mode: 0644
    owner: root
    group: root
    dest: /etc/haproxy/haproxy.cfg
    src: haproxy.cfg.j2
    force: yes


# Add a cronjob to reload the HAProxy configuration every hour
#
- name: Add haproxy reload cronjob
  cron:
    name: "haproxy reload"
    special_time: hourly
    job: "systemctl reload haproxy"
    state: present
