---
## The generic directory /var/containers/{{ project_id }}
## for LXD container persistent storage has already been
## set up by generic host-setup playbooks
## Further project-specific container directories should be
## added here
## -----------------------------------------------------------

## Directories for project-specific LXD container persistent storage
## -----------------------------------------------------------------

### Certbot directory

- name: Create a directory to mount in certbot containers
  file:
    path: "/var/containers/{{ project_id }}/certbot"
    state: directory
    mode: '0755'


### TLS certificates directory

- name: Create a directory to mount in containers needing TLS certificates
  file:
    path: "/var/containers/{{ project_id }}/tls"
    state: directory
    mode: '0755'


### HAProxy directory

- name: Create a directory to mount in HAProxy containers needing TLS certificates
  file:
    path: "/var/containers/{{ project_id }}/tls/haproxy"
    state: directory
    mode: '0755'


### Website directories

- name: Create a directory for website content
  file:
    path: "/var/containers/{{ project_id }}/website"
    state: directory
    mode: '0755'

- name: Create a directory for grav content
  file:
    path: "/var/containers/{{ project_id }}/website/grav"
    state: directory
    mode: '0755'
