#cloud-config
package_upgrade: false
write_files:
- path: /usr/local/bin/iptables-rules-project.sh
  content: |
    #!/bin/sh
    IPT="/sbin/iptables"
    #
    # HTTP and HTTPS already allowed in module setup. Add further ports here if needed for the project
    #
  permissions: '0770'
  owner: root:root
