---
# SPDX-FileCopyrightText: 2022 Wilfred Nicoll <xyzroller@rollyourown.xyz>
# SPDX-License-Identifier: GPL-3.0-or-later


# Set up grav scheduler cron job
#
- name: Set up grav scheduler cron job
  cron:
    name: "grav-scheduler-cron"
    user: www-data
    month: "*"
    day: "*"
    weekday: "*"
    hour: "*"
    minute: "*"
    job: "cd /var/www/grav-admin;/usr/bin/php bin/grav scheduler 1>> /dev/null 2>&1"
    state: present
