---
- name: Set up local machine
  hosts: local
  
  vars_files:
    - "{{ playbook_dir }}/../configuration/config_path.yml"
    - "{{ local_config_path }}"
    - "{{ host_config_path }}"
  
  vars:
    ansible_user: "{{ local_non_root_user }}"
    ansible_become: yes
    ansible_become_password: "{{ local_non_root_user_password }}"

  roles:
    - role: generate-ssh-keys
    - role: install-wireguard
    - role: set-up-wireguard
    - role: install-and-set-up-lxd
    - role: install-packer
    - role: install-terraform
