---
- name: Make sure certbot packages are uninstalled and purged
  apt:
    name: certbot
    update_cache: no
    purge: yes
    state: absent
  register: changes_made


- name: Make sure snapd is installed
  apt:
    name: snapd
    update_cache: yes
    state: present
  register: changes_made


- name: Install certbot snap package
  snap:
    name: certbot
    classic: yes
    state: present
  register: changes_made


- name: Prepare the Certbot command
  file:
    src: /snap/bin/certbot
    dest: /usr/bin/certbot
    state: link


- name: Create the letsencrypt configuration directory for mounting as persistent storage
  file:
    path: /etc/letsencrypt
    state: directory
    mode: '0755'
