---
- name: Copy self-signed cert to mount directory for haproxy ssl
  copy:
    mode: 0640
    owner: root
    group: root
    dest: /var/containers/ryo-grav-cms/tls/haproxy/ryo.pem
    src: ryo.pem
    force: yes
