## If this file is moved to a different location, 
# update config_path.yml with the new path to the file

## WARNING: After adding configuration, never push this file, with secrets, 
# to a repository or publish in any other way!


#-----------------------
# REQUIRED Configuration
#-----------------------

# Local user configuration
#-------------------------

# Enter your non-root username for this machine
# (note: the user must be a member of the sudo group
# - `useradd <username> sudo` if not already a sudo user)
local_non_root_user: <USER_NAME>

# SECRET: Enter your non-root user password for this machine. Enter "" if
# no password is required (e.g. with a Multipass VM)
local_non_root_user_password: <PASSWORD>


# Basic host configuration
#-------------------------

# Add the public IPv4 address of your host server here. 
# !! Also add to the inventory.ini file
host_public_ip: <IP ADDRESS>

# Set the default SSH port, as provided by your server hosting provider
host_initial_ssh_port: 22


# Host user configuration
#------------------------

# Set the default root username here (probably 'root'), as provided by 
# your server hosting provider
host_root_user: root

# Set the default root password here, as provided by your server 
# hosting provider
host_root_password: <INITIAL PASSWORD>

# Define a non-root username
host_non_root_user: <USER_NAME>

# SECRET: Set a strong user password and a random salt here. 
# Create a random salt with:  'tr -dc A-Za-z0-9 </dev/urandom | head -c 12 ; echo ""'
host_non_root_user_password: <PASSWORD>
host_non_root_password_salt: <SALT>

# Add an LXD core trust password here, can be generated, 
# for example, with 'tr -dc A-Za-z0-9 </dev/urandom | head -c 12 ; echo ""'
lxd_core_trust_password: <PASSWORD>

# Change according to the available storage on the host. 
# Set to leave at least ~4GB for the operating system
lxd_storage_pool_size: 50GB


# Project configuration
#----------------------

# Set the domain to be used for the project. The DNS A record for the project's 
# domain must be set to point to the public IPv4 address of your host server
project_domain_name: <DOMAIN>

# Set a strong password for the grav_admin user - minimum 8 chars, at least 
# one number, one uppercase and one lowercase letter
grav_admin_password: <PASSWORD>

# Enter an email address for the administrator of this project, 
# this will be used for letsencrypt certificates and for the grav_admin user
project_admin_email: <EMAIL ADDRESS>



#----------------------------------------------------------------------------
# DEFAULT Configuration - leave as default unless you know what you are doing
#----------------------------------------------------------------------------

# Local machine configuration switches
#-------------------------------------

# Whether to generate SSH keys (change to 'false' if SSH keys are already available)
generate_ssh_keys: true

# Whether to install wireguard (change to 'false' if wireguard already installed on this machine)
install_local_wireguard: true

# Whether to create new wireguard configuration for local machine to host 
# communication (change to 'false' if wireguard configuration generated manually)
set_up_local_wireguard: true

# Whether to install lxd (change to 'false' if lxd already installed on this machine)
install_local_lxd: true

# Whether to install packer (change to 'false' if packer already installed on this machine)
install_local_packer: true

# Whether to install terraform (change to 'false' if terraform already installed on this machine)
install_local_terraform: true


# Default host configuration
#---------------------------

# Leave as default or change according to preference
host_hostname: ryo-grav-cms

# Leave as default or change according to preference
host_new_ssh_port: 2222

# Leave as default or change according to preference
host_wireguard_port: 52222

# Leave as default or change according to preference. !! If changed, 
# also change in the inventory.ini file
host_wireguard_address: "10.0.1.1"

# Leave as default or change according to preference
host_wireguard_address_range: "10.0.1.0/24"

# Leave as default if wireguard configuration is generated by local-setup.sh
# script, otherwise enter the path host server wireguard configuration file here
# Generate wireguard configuration for the host server and client(s), e.g. using 
# the tool https://www.wireguardconfig.com/, see ***[LINK TO rollyourown.xyz project instructions here]***
host_wireguard_configuration_file: /home/{{ local_non_root_user }}/ryo-host.conf


# Default host LXD configuration
#-------------------------------

# Leave as default or change according to preference
lxd_br0_ip_addr: '10.10.1.1/24'

# Leave as default or change according to preference
lxd_dmz_network_part: '10.10.10'

# Leave as default or change according to preference
lxd_frontend_network_part: '10.10.11'

# Leave as default or change according to preference
lxd_backend_network_part: '10.10.12'


# Default host user configuration
#--------------------------------

# Leave as default if SSH keys are generated by local-setup.sh script, 
# otherwise enter the paths to the non-root user's SSH private and public keys here
host_non_root_user_ssh_private_key_file_path: "/home/{{ local_non_root_user }}/.ssh/ryo_id_ssh_rsa" 
host_non_root_user_ssh_public_key_file_path: "/home/{{ local_non_root_user }}/.ssh/ryo_id_ssh_rsa.pub"

# Change to 'true' if 2FA should be used for non-root user login via public 
# SSH port and enter the path to the non-root user's google authenticator 
# configuration file
host_non_root_use_google_authenticator: false
host_non_root_user_google_authenticator_file: <PATH>


#-----------------------------------------------
# Project-specific configuration - do not change
#-----------------------------------------------

# Do not change. True if needed for this project, otherwise false
host_ipv4_packet_forwarding: true

# Do not change. True if needed for this project, otherwise false
host_veth0_enable: false

# Do not change. Set if needed for this project, otherwise "none"
host_veth0_macaddress: "none"

# Do not change. Set if needed for this project, otherwise "none"
host_veth0_ipaddress: "none"
