---
local_config_path: <PATH>    # Enter the path your local_configuration.yml file here
host_config_path: <PATH>     # Enter the path your host_configuration.yml file here
project_config_path: <PATH>  # Enter the path your project_configuration.yml file here