---
## Template configuration file for the rollyourown.xyz project: ryo-simple-blog-grav
## https://rollyourown.xyz/projects/ ...

## TODO: complete link here ^^^

## 1. Copy to a location on your local machine and rename as desired (e.g. rename as local_configuration.yml)
## 2. Enter the path to this new file in config_path.yml
## 3. Change the configuration parameters below for your deployment

## WARNING: Never push the local copy of the file, with secrets, to a repository or publish in any other way!

#-------------------------
# Local user configuration
#-------------------------

# Enter your non-root username
local_non_root_user: <USER_NAME>

# SECRET: Enter your non-root user password
local_non_root_user_password: <PASSWORD>


#---------
# Switches
#---------

# Whether to generate SSH keys (change to 'false' if SSH keys are already available)
generate_ssh_keys: true

# Whether to install wireguard (change to 'false' if wireguard already installed on this machine)
install_local_wireguard: true

# Whether to create wireguard configuration for local machine to host communication (change to 'false' if wireguard already set up)
set_up_local_wireguard: true

# Whether to install lxd (change to 'false' if lxd already installed on this machine)
install_local_lxd: true

# Whether to install packer (change to 'false' if packer already installed on this machine)
install_local_packer: true

# Whether to install terraform (change to 'false' if terraform already installed on this machine)
install_local_terraform: true
