---
## Template configuration file for the rollyourown.xyz project: ryo-simple-blog-grav
## https://rollyourown.xyz/projects/ ...

## TODO: complete link here ^^^

## 1. Copy to a location on your local machine and rename as desired (e.g. rename as host_configuration.yml)
## 2. Enter the path to this new file in config_path.yml
## 3. Change the configuration parameters below for your deployment

## WARNING: Never push the local copy of the file, with secrets, to a repository or publish in any other way!

#------------------------
# Host user configuration
#------------------------

# Set the default root username here (probably 'root'), as provided by your server hosting provider
host_root_user: root

# Set the default root password here, as provided by your server hosting provider
host_initial_root_password: <INITIAL PASSWORD>

# SECRET: Set a new, strong root password and a random salt here. Create a random salt with:  'tr -dc A-Za-z0-9 </dev/urandom | head -c 12 ; echo ""'
host_new_root_password: <PASSWORD>
host_new_root_password_salt: <SALT>

# Define a non-root username
host_non_root_user: <USER_NAME>

# SECRET: Set a strong user password and a random salt here. Create a random salt with:  'tr -dc A-Za-z0-9 </dev/urandom | head -c 12 ; echo ""'
host_non_root_user_password: <PASSWORD>
host_non_root_password_salt: <SALT>

# Leave as default if SSH keys are generated by local-setup.sh script, otherwise enter the paths to the non-root user's SSH private and public keys here
host_non_root_user_ssh_private_key_file_path: "/home/{{ local_non_root_user }}/.ssh/id_ssh_rsa" 
host_non_root_user_ssh_public_key_file_path: "/home/{{ local_non_root_user }}/.ssh/id_ssh_rsa.pub"

# Change to 'true' if 2FA should be used for non-root user login via public SSH port and enter the path to the non-root user's google authenticator configuration file
host_non_root_use_google_authenticator: false
host_non_root_user_google_authenticator_file: <PATH>


#-------------------------
# Basic host configuration
#-------------------------

# Add the public IPv4 address of your host server here. !! Also add to the inventory.ini file
host_public_ip: <IP ADDRESS>

# Leave as default or change according to preference
host_hostname: rollyourown

# Do not change. True if needed for this project, otherwise false
host_ipv4_packet_forwarding: true

# Do not change. True if needed for this project, otherwise false
host_veth0_enable: false

# Do not change. Set if needed for this project, otherwise "none"
host_veth0_macaddress: "none"

# Do not change. Set if needed for this project, otherwise "none"
host_veth0_ipaddress: "none"

# Set the default SSH port, as provided by your server hosting provider
host_initial_ssh_port: 22

# Leave as default or change according to preference
host_new_ssh_port: 2222

# Leave as default or change according to preference
host_wireguard_port: 52222

# Leave as default or change according to preference. !! Also add to the inventory.ini file
host_wireguard_address: "10.0.1.1"

# Leave as default or change according to preference
host_wireguard_address_range: "10.0.1.0/24"

# Generate wireguard configuration for the host server and client(s), see ***[LINK TO rollyourown.xyz project instructions here]***
# MOVE TO project instructions: e.g. using the tool https://www.wireguardconfig.com/
#
# Leave as default if wireguard configuration is generated by local-setup.sh script, otherwise enter the path host server wireguard configuration file here
host_wireguard_configuration_file: /home/{{ local_non_root_user }}/ryo-host.conf


#-----------------------
# Host LXD configuration
#-----------------------

# Add an LXD core trust password here 
lxd_core_trust_password: <PASSWORD>

# Change according to the available storage on the host
lxd_storage_pool_size: 50GB

# Leave as default or change according to preference
lxd_br0_ip_addr: '10.10.1.1/24'

# Leave as default or change according to preference
lxd_dmz_network_part: '10.10.10'

# Leave as default or change according to preference
lxd_frontend_network_part: '10.10.11'

# Leave as default or change according to preference
lxd_backend_network_part: '10.10.12'
