---
## Note: LXD container control node is not currently used / supported for rollyourown.xyz projects
## Container nesting (LXD containers used in image build process within the LXC container control node)
## is not reliable - for example snapd cannot install snaps within a nested container

- name: Set up local machine
  hosts: local
  
  vars_files:
    - "{{ playbook_dir }}/../configuration/config_path.yml"
    - "{{ configuration_path }}"
  
  vars:
    ansible_user: "{{ local_non_root_user }}"
    ansible_become: yes
    ansible_become_password: "{{ local_non_root_user_password }}"

  roles:
    - role: generate-ssh-keys
    - role: install-sshpass
    - role: install-wireguard
    - role: set-up-wireguard
    - role: install-and-set-up-lxd
    - role: install-packer
    - role: install-terraform
