---
## Note: Although it is our goal to have a control node running as a WSL app, currently there are limitations
## in WSL preventing this - for example missing systemd prevents the wireguard interface for communication
## with the host server from starting automatically and snapd not working so that LXD cannot be installed via
## snap. If WSL is updated in future to support systemd and snapd, we will return to this as the easiest way
## to deploy rollyourown.xyz projects from a Windows computer

- name: Set up local machine
  hosts: local
  
  vars_files:
    - "{{ playbook_dir }}/../configuration/config_path.yml"
    - "{{ configuration_path }}"
  
  vars:
    ansible_user: "{{ local_non_root_user }}"
    ansible_become: yes
    ansible_become_password: "{{ local_non_root_user_password }}"

  roles:
    - role: generate-ssh-keys
    - role: install-sshpass
    - role: install-wireguard
    - role: set-up-wireguard
    - role: install-and-set-up-lxd
    - role: install-packer
    - role: install-terraform
